=== 19i318/Web-Tech/Ex-2b/ccis.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ccis_college">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Lecturer" maxOccurs="unbounded" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="Name"/>
              <xs:element type="xs:string" name="Nationality"/>
              <xs:element type="xs:integer" name="Experience"/>
              <xs:element type="xs:string" name="Phone" maxOccurs="3" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="degree" use="optional" default="phd"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== 19i318/Web-Tech/Ex-2b/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<ccis_college xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="U:\Code\Ex-4\ccis.xsd">
  <Lecturer degree="masters">
    <Name> Putin </Name>
    <Nationality> Russian </Nationality>
    <Experience> 2 </Experience>
  </Lecturer>
  <Lecturer>
    <Name> Trump </Name>
    <Nationality> American </Nationality>
    <Experience> 4 </Experience>
    <Phone> Samsung </Phone>
    <Phone> Blackberry </Phone>
    <Phone> Apple </Phone>
  
  </Lecturer>
</ccis_college>
